name: Create Release (to deploy)
on:
  workflow_dispatch:
    inputs:
      commitSha:
        type: string
        description: The commit SHA to deploy. Ensure your provide a commit that has successfully run the CI pipeline.
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      discussions: write
      packages: write
      pages: write
      pull-requests: write
      repository-projects: write
      security-events: write
      statuses: write
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M')"
      - name: Get commit ref
        id: commit
        run: |
          echo ::set-output name=longSHA::$(git rev-parse ${{ github.event.inputs.commitSha }})
          echo ::set-output name=shortSHA::$(git rev-parse --short ${{ github.event.inputs.commitSha }})
      - name: Log commit refs
        run: |
          echo "long sha: ${{ steps.commit.outputs.longSHA }}"
          echo "short sha: ${{ steps.commit.outputs.shortSHA }}"
      - name: Add status check # so the check statuses thing can be tested
        uses: Sibz/github-status-action@v1
        with:
          authToken: ${{ github.token }}
          context: 'TestStatus'
          description: 'All good'
          state: 'success'
          sha: ${{ steps.commit.outputs.longSHA }}
      - name: Check pipeline statuses
        uses: tamj0rd2/pipeline-status-action@v1.2.0
        with:
          checkNames: TestStatus
          slackWebhookURL: abc123
          sha: ${{ steps.commit.outputs.shortSHA }}
          timeoutMinutes: "1"
      - name: Do release
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ github.token }}" \
            $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases \
            -d '{"tag_name":"${{ steps.commit.outputs.shortSHA }}","target_commitish":"${{ steps.commit.outputs.longSHA }}","name":"${{ steps.commit.outputs.shortSHA }}","body":"automated :)","draft":false,"prerelease":false,"generate_release_notes":false}' \
            --fail
