name: Create Release (to deploy)
on:
  workflow_dispatch:
    inputs:
      commitSha:
        type: string
        description: The commit SHA to deploy. Ensure your provide a commit that has successfully run the CI pipeline.
        required: true
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date '+%Y%m%d%H%M')"
      - name: Get long commit ref
        id: commit
        run: |
          echo "::set-output name=longSHA::$(git rev-parse ${{ github.event.inputs.commitSha }})"
      - name: Do release
        run: |
          curl \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            $GITHUB_API_URL/repos/$GITHUB_REPOSITORY/releases \
            -d '{"tag_name":"tags/${{ github.event.inputs.commitSha }}","target_commitish":"${{ github.commit.outputs.longSHA }}","name":"${{ github.event.inputs.commitSha }}","body":"automated :)","draft":false,"prerelease":false,"generate_release_notes":true}' \
            --fail
